package com.example.demo.model;

import java.io.Serializable;

public class Handle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handle.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handle.handle_name
     *
     * @mbg.generated
     */
    private String handleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handle.handle_id
     *
     * @mbg.generated
     */
    private String handleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handle.prev_handle_id
     *
     * @mbg.generated
     */
    private String prevHandleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column handle.next_handle_id
     *
     * @mbg.generated
     */
    private String nextHandleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table handle
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handle.id
     *
     * @return the value of handle.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handle.id
     *
     * @param id the value for handle.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handle.handle_name
     *
     * @return the value of handle.handle_name
     *
     * @mbg.generated
     */
    public String getHandleName() {
        return handleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handle.handle_name
     *
     * @param handleName the value for handle.handle_name
     *
     * @mbg.generated
     */
    public void setHandleName(String handleName) {
        this.handleName = handleName == null ? null : handleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handle.handle_id
     *
     * @return the value of handle.handle_id
     *
     * @mbg.generated
     */
    public String getHandleId() {
        return handleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handle.handle_id
     *
     * @param handleId the value for handle.handle_id
     *
     * @mbg.generated
     */
    public void setHandleId(String handleId) {
        this.handleId = handleId == null ? null : handleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handle.prev_handle_id
     *
     * @return the value of handle.prev_handle_id
     *
     * @mbg.generated
     */
    public String getPrevHandleId() {
        return prevHandleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handle.prev_handle_id
     *
     * @param prevHandleId the value for handle.prev_handle_id
     *
     * @mbg.generated
     */
    public void setPrevHandleId(String prevHandleId) {
        this.prevHandleId = prevHandleId == null ? null : prevHandleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column handle.next_handle_id
     *
     * @return the value of handle.next_handle_id
     *
     * @mbg.generated
     */
    public String getNextHandleId() {
        return nextHandleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column handle.next_handle_id
     *
     * @param nextHandleId the value for handle.next_handle_id
     *
     * @mbg.generated
     */
    public void setNextHandleId(String nextHandleId) {
        this.nextHandleId = nextHandleId == null ? null : nextHandleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handle
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", handleName=").append(handleName);
        sb.append(", handleId=").append(handleId);
        sb.append(", prevHandleId=").append(prevHandleId);
        sb.append(", nextHandleId=").append(nextHandleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}