package com.example.demo.model;

public class Strategy{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.strategy_name
     *
     * @mbg.generated
     */
    private String strategyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.class_path
     *
     * @mbg.generated
     */
    private String classPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table strategy
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.id
     *
     * @return the value of strategy.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.id
     *
     * @param id the value for strategy.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.strategy_name
     *
     * @return the value of strategy.strategy_name
     *
     * @mbg.generated
     */
    public String getStrategyName() {
        return strategyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.strategy_name
     *
     * @param strategyName the value for strategy.strategy_name
     *
     * @mbg.generated
     */
    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName == null ? null : strategyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy.class_path
     *
     * @return the value of strategy.class_path
     *
     * @mbg.generated
     */
    public String getClassPath() {
        return classPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy.class_path
     *
     * @param classPath the value for strategy.class_path
     *
     * @mbg.generated
     */
    public void setClassPath(String classPath) {
        this.classPath = classPath == null ? null : classPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", strategyName=").append(strategyName);
        sb.append(", classPath=").append(classPath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}