package com.sihui.mybatis.model;

import lombok.Data;

import java.io.Serializable;

@Data
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_id
     *
     * @mbg.generated Thu Dec 05 16:23:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_name
     *
     * @mbg.generated Thu Dec 05 16:23:49 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.c_age
     *
     * @mbg.generated Thu Dec 05 16:23:49 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated Thu Dec 05 16:23:49 CST 2019
     */
    private static final long serialVersionUID = 1L;
}