package com.example.demo.mapper;

import com.example.demo.model.Handle;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HandleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handle
     *
     * @mbg.generated
     */
    int insert(Handle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handle
     *
     * @mbg.generated
     */
    Handle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handle
     *
     * @mbg.generated
     */
    List<Handle> selectAll();

    Handle seletByHandleId(String handleId);

    Handle seletFirstHandle();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table handle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Handle record);
}