package com.example.demo.mapper;

import com.example.demo.model.Strategy;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StrategyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    int insert(Strategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    Strategy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    Strategy selectByName(String straegyName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    List<Strategy> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table strategy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Strategy record);
}